name: osselbot
description: A stupid discord bot made for stupid people.
version: 3.0.0
homepage: https://nicolor.tech/bot

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  nyxx: ^2.0.0-rc.3
  nyxx_interactions: ^2.0.0-rc.5
  nyxx_commander: ^2.0.0-rc.5
  path: ^1.7.0


dev_dependencies:
  pedantic: ^1.9.0
